apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - command:
        - sleep
        - infinity
        image: quay.io/prometheus/busybox:latest
        name: busybox