apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  annotations:
    "service.binding/test": "path={.metadata.name}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - command:
        - sleep
        - infinity
        image: quay.io/prometheus/busybox:latest
        name: busybox